name: Run Notion to Telegram Service Cron

on:
  schedule:
    - cron: '*/2 * * * *' # Setiap 10 menit
  workflow_dispatch: # Bisa dijalankan manual juga

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-dotenv

    - name: Pull latest id_sent.json from main branch
      run: |
        git fetch origin main
        git checkout origin/main -- id_sent.json || echo "No existing id_sent.json"

    - name: Create .env file from GitHub Secrets
      env:
        ENV_VARS: ${{ secrets.env }}
      run: |
        echo "$ENV_VARS" > .env

    - name: Run Python script
      env:
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        python notion_to_telegram.py

    - name: Commit and push updated id_sent.json
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add id_sent.json
        git commit -m "Update id_sent.json [skip ci]" || echo "No changes to commit"
        git push
