name: Run Notion to Telegram Service Cron

on:
  schedule:
    - cron: '*/2 * * * *'  # Setiap 2 menit
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-dotenv

    - name: Buat file .env dari GitHub Secrets
      env:
        ENV_VARS: ${{ secrets.env }}
      run: |
        echo "$ENV_VARS" > .env

    - name: Jalankan script Python
      run: |
        python notion_to_telegram.py

    - name: Commit and push updated id_sent.json
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add id_sent.json
        git commit -m "Update id_sent.json [skip ci]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
